### ISSUE TITLE
Migrate repository elsewhere?

### ISSUE THREAD

**Issue by kandersolar** [openpvtools/pv-foss-engagement#1]
In part to shift it towards being a community project and in part because I don't like seeing my handle in the webpage url, I want to rehome this repository somewhere else.  @wholmgren would it be a good fit for the [openpvtools](https://github.com/openpvtools/) organization?

**Comment by wholmgren** [comment]
yeah, I like that idea - go for it!

**Comment by kandersolar** [comment]
It is done 🎉
