### ISSUE TITLE
Add pvcaptest to tracker?

### ISSUE THREAD

**Issue by kandersolar** [openpvtools/pv-foss-engagement#4]
Hi @bt-, I wonder if you'd like pvcaptest to be included in this project's [statistics tracking website](https://openpvtools.github.io/pv-foss-engagement/)? Adding pvcaptest would mostly mean adding a new [notebook](https://github.com/openpvtools/pv-foss-engagement/tree/main/sphinx/source/project) using one of the others as a starting point.  The GitHub stats can be pulled without anything else, but unfortunately tracking ReadTheDocs statistics requires admin access, so that would require giving my RTD account ([kanderso-nrel](https://readthedocs.org/profiles/kanderso-nrel/)) access to the RTD project.  Fine to not do that if you don't want, although not having docs statistics results in a rather boring report :P

Anyway happy to help if you're interested.  Thanks!

**Comment by bt-** [comment]
Hi, @kanderso-nrel, yes, I'm interested in adding pvcaptest. Thanks for asking. I assume I should fork this project, create the new notebook, and then make a pull request? I'll take at giving you RTD access. I don't see any issues with that. Edit - I am looking at RTD and it seems like the only way to share is to have a business account? Do the other projects all have business accounts or are they setup differently?

**Comment by kandersolar** [comment]
> fork this project, create the new notebook, and then make a pull request

Yep!  And in addition to a new notebook file, the `index.rst` file will need another `grid-item-card` entry.

Also I just realized it might be difficult to make a new notebook without the RTD data being available.  Once the RTD access is set up, I can trigger the [github action](https://github.com/openpvtools/pv-foss-engagement/actions/workflows/fetch-rtd-data.yml) to fetch an initial dataset and commit it to `main`, which you can then use for a notebook. 

> Do the other projects all have business accounts

The other projects have any kind of special business account as far as I'm aware... I think it should be enough to add it via the "Maintainers" page, which should be here: https://readthedocs.org/dashboard/pvcaptest/users/

**Comment by bt-** [comment]
Thanks for pointing me to the right place to add you as a maintainer on RTD. I just did that, so you should see an invite. Let me know when you've fetched an initial dataset.  I started editing a new ipynb and did run into it looking for data that isn't there.

**Comment by kandersolar** [comment]
Thanks @bt-!  If you update your branch with `upstream/main`, there's a new RTD data file that should be accessible with `df = utils.get_rtd_analytics_data('pvcaptest')`.
