### ISSUE TITLE
Missing repo alternative: solarfactors

### ISSUE THREAD

**Issue by echedey-ls** [openpvtools/pv-foss-engagement#8]
https://github.com/pvlib/solarfactors is missing in the list of repos, although the original pvfactors is listed.
I'd like to see solarfactors listed too.

**Comment by kandersolar** [comment]
I've just added solarfactors to the ReadTheDocs data scraper, so there's a data file available now on `main`.  Want to make a new notebook for solarfactors?

**Comment by echedey-ls** [comment]
Closing via #9
